version: '2'

services:
  redis:
    restart: always
    image: redis:alpine
  
  imserver:
    restart: always
    image: imserver:standard
    ports:
      - "3109:3109"
      - "3101:3101"
      - "3102:3102"
      - "3103:3103"
    volumes:
      - ./volumes/imserver/etc:/app/etc:Z
      - ./volumes/imserver/log:/var/log:Z
    command: /supervisor.sh

  postgres:
    restart: always
    image: postgres:alpine
    volumes:
      - ./project/dbs:/var/lib/postgresql:Z
    env_file: ./project/app/env.docker

  django:
    restart: always
    image: django:passport
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    ports:
      - "5005:5005"  
      - "9009:9009"  
    volumes:
      - ./project/app:/app:Z
      - ./project/log:/var/log/:Z
      - ./project/app/env.docker:/app/.env:Z
      - ./project/etc/supervisor:/etc/supervisor:Z
    env_file: ./project/app/env.docker
    command: /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
