version: '2'

services:
  redis:
    restart: always
    image: redis:alpine
  
  imserver:
    restart: always
    image: imserver:standard
    ports:
      - "3109:3109"
      - "3101:3101"
      - "3102:3102"
      - "3103:3103"
    volumes:
      - ./volumes/imserver/etc:/app/etc:Z
      - ./volumes/imserver/log:/var/log:Z
    command: /supervisor.sh

  mysql:
    restart: always
    image: mysql:5.7.25
    volumes:
      - ./project/dbs:/var/lib/postgresql:Z
    environment: 
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    command: --default-authentication-plugin=mysql_native_password
